### PR TITLE
Add a technology field in the add app form #63 - implementation

### PR DESCRIPTION
**Pull request by Sugahzor**

### CODE REVIEW

**Comment by razvanpavel** [comment]
No backend support at the moment. @aniri @RaduCStefanescu please confirm

**Comment by aniri** [comment]
@razvanpavel related backend tasks are https://github.com/code4romania/civichq-api/issues/80 and https://github.com/code4romania/civichq-api/issues/81

**Comment by paul-ghiran** [comment]
Implementation changed in https://github.com/code4romania/civichq-client/pull/91

**Comment by aniri** [comment]
a newer implementation exists in #91 after new ux suggestions. this pull should be closed.

**Pull request closed without merging**
