### PR TITLE
Upgrade Angular from 2 to 7

### PR DESCRIPTION
**Pull request by lrdTnc**
*improved JWT Auth using http interceptor (no more localStorage saving at the moment)
*clean-up code
*removed webpack (using ng-cli)
*updated descriptions
*updated dependencies

*known problems: ng-select (used in hashtags) doesn't seem to work anymore, needs further changes*

### CODE REVIEW

**Comment by lrdTnc** [comment]
https://github.com/code4romania/civichq-client/issues/49

**Comment by bogdanconstantinescu** [comment]
Mi se pare ok upgrade-ul desi merge chiar pana la ultima versiune.
Cu [acest package.json](https://gist.github.com/bogdanconstantinescu/11796e60e38d8923462530d222bb1cad) si un `npm install` poate fi adus la zi, n-am vazut sa fie erori (ce-i drept nici n-am reusit sa am backendul 100% functional), dar merita testat.

Ce n-am inteles exact e de ce au fost transformate observables in promise-uri cu `.toPromise()` - intr-adevar, nu exista business logic facut cu Rx dar chiar si asa, n-as schimba ceva facut cu observables in promise-uri.

**Comment by lrdTnc** [comment]
Oh super, voi lua acel package.json și voi testa și actualiza pull request -ul! Thanks a lot!

Am transformat toate acele observables din cauza ca îmi place mie prea mult async await :)) si mi se pare că e codul mai simplu

Cred că într-un singur loc s-ar preta observable, si anume la tag.service

**Comment by lrdTnc** [comment]
Took the suggested package.json  and also did change the ngx-captcha and @angular-devkit/build-angular versions to the latest. 

Tested with a working api and it seems fine!

**Pull request merged**
